#cloud-config

---
coreos:
  etcd:
    discovery: "https://discovery.etcd.io/1d77508dc31cf372d517ed2e96e8f5cf"
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls:  "http://$private_ipv4:2380"
    listen_client_urls:          "http://0.0.0.0:2379"
    listen_peer_urls:            "http://$private_ipv4:2380"
  units:
  - name: marathon.service
    command: start
    enable: true
    content: |-
      [Unit]
      Description=Marathon
      After=mesos-master.service
      Requires=docker.service

      [Service]
      Restart=on-failure
      RestartSec=20
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker rm -f marathon
      ExecStartPre=-/usr/bin/docker pull mesosphere/marathon:v1.7.166
      ExecStart=/usr/bin/sh -c "/usr/bin/docker run \
          --restart=always \
          --name marathon \
          -e LIBPROCESS_PORT=9090 \
          -p 80:8080 \
          -p 9090:9090 \
          mesosphere/marathon:v1.7.166 \
          --master zk://172.18.4.5:2181,172.18.4.6:2181,172.18.4.7:2181/mesos \
          --zk zk://172.18.4.5:2181,172.18.4.6:2181,172.18.4.7:2181/marathon \
          --checkpoint \
          --hostname 172.18.4.4"
      ExecStop=/usr/bin/docker stop marathon

      [Install]
      WantedBy=multi-user.target
