#cloud-config

---
coreos:
  etcd:
    discovery: "https://discovery.etcd.io/1d77508dc31cf372d517ed2e96e8f5cf"
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls:  "http://$private_ipv4:2380"
    listen_client_urls:          "http://0.0.0.0:2379"
    listen_peer_urls:            "http://$private_ipv4:2380"
  units:
  - name: consul.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=Consul
      After=docker.service
      Requires=docker.service
      Wants=consul-announce.service
      Before=consul-announce.service

      [Service]
      Restart=on-failure
      RestartSec=20
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker rm -f consul
      ExecStartPre=-/usr/bin/docker pull r.j3ss.co/consul:latest
      ExecStart=/usr/bin/sh -c "/usr/bin/docker run \
        -e SERVICE_IGNORE=true \
        --net=host \
        --volume /etc/consul.d:/etc/consul.d \
        --volume /opt/consul:/opt/consul \
        --name=consul \
        r.j3ss.co/consul:latest \
          agent \
          -server \
          -bootstrap-expect 4 \
          -data-dir /opt/consul \
          -config-dir /etc/consul.d \
          -advertise $private_ipv4"
      ExecStop=/usr/bin/docker stop consul

      [Install]
      WantedBy=multi-user.target
  - name: consul-announce.service
    command: start
    content: |
      [Unit]
      Description=Consul Announcer
      PartOf=consul.service
      After=consul.service
      [Service]
      Restart=on-failure
      RestartSec=20
      Environment=NOMAD_HOSTS=172.18.4.5,172.18.4.6,172.18.4.7,172.18.4.8,172.18.4.9
      ExecStart=/bin/bash /etc/consul/join.sh
  - name: nomad.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=Nomad Server
      After=docker.service consul.service consul-announce.service
      Requires=docker.service consul.service

      [Service]
      Restart=on-failure
      RestartSec=20
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker rm -f nomad
      ExecStartPre=-/usr/bin/docker pull r.j3ss.co/nomad:latest
      ExecStart=/usr/bin/sh -c "/usr/bin/docker run \
        -e SERVICE_IGNORE=true \
        --net=host \
        --volume /etc/nomad.d:/etc/nomad.d \
        --name=nomad \
        r.j3ss.co/nomad:latest \
          agent -config=/etc/nomad.d/server.hcl"
      ExecStop=/usr/bin/docker stop nomad

      [Install]
      WantedBy=multi-user.target
write_files:
- path: "/etc/nomad.d/server.hcl"
  permissions: "0644"
  owner: "root"
  content: |
    data_dir = "/etc/nomad.d"

    server {
      enabled          = true
      bootstrap_expect = 4
    }
- path: "/etc/consul/join.sh"
  permissions: "0744"
  owner: "root"
  content: |
    #!/bin/bash
    set -e
    set -o pipefail
    set -x

    # Add the hosts.
    if [ -n "${NOMAD_HOSTS+1}" ]; then
      IFS=',' read -r -a nhosts <<< "$NOMAD_HOSTS"
      for index in "${!nhosts[@]}"; do
        /usr/bin/docker run --rm --net host r.j3ss.co/consul:latest join "$index"
      done
    fi
