#cloud-config

---
coreos:
  etcd:
    discovery: "https://discovery.etcd.io/1d77508dc31cf372d517ed2e96e8f5cf"
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls:  "http://$private_ipv4:2380"
    listen_client_urls:          "http://0.0.0.0:2379"
    listen_peer_urls:            "http://$private_ipv4:2380"
  units:
  - name: nomad.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=Nomad Agent
      After=docker.service consul.service consul-announce.service
      Requires=docker.service consul.service

      [Service]
      Restart=on-failure
      RestartSec=20
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker rm -f nomad
      ExecStartPre=-/usr/bin/docker pull r.j3ss.co/nomad:latest
      ExecStart=/usr/bin/sh -c "/usr/bin/docker run \
        -e SERVICE_IGNORE=true \
        --net=host \
        --volume /etc/nomad.d:/etc/nomad.d \
        --name=nomad \
        r.j3ss.co/nomad:latest \
          agent -config=/etc/nomad.d/client.hcl"
      ExecStop=/usr/bin/docker stop nomad

      [Install]
      WantedBy=multi-user.target
write_files:
- path: "/etc/nomad.d/client.hcl"
  permissions: "0644"
  owner: "root"
  content: |
    data_dir = "/etc/nomad.d"

    client {
      enabled          = true
      servers = ["172.18.4.5:4647","172.18.4.6:4647","172.18.4.7:4647","172.18.4.8:4647","172.18.4.9:4647"]
    }
