#cloud-config

---
coreos:
  etcd:
    discovery: "https://discovery.etcd.io/1d77508dc31cf372d517ed2e96e8f5cf"
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls:  "http://$private_ipv4:2380"
    listen_client_urls:          "http://0.0.0.0:2379"
    listen_peer_urls:            "http://$private_ipv4:2380"
write_files:
- path: "/home/vmuser/.bashrc"
  permissions: "0777"
  owner: "vmuser"
  content: |
    # /etc/skel/.bashrc
    #
    # This file is sourced by all *interactive* bash shells on startup,
    # including some apparently interactive shells such as scp and rcp
    # that can't tolerate any output.  So make sure this doesn't display
    # anything or bad things will happen !


    # Test for an interactive shell.  There is no need to set anything
    # past this point for scp and rcp, and it's important to refrain from
    # outputting anything in those cases.
    if [[ $- != *i* ]] ; then
            # Shell is non-interactive.  Be done now!
            return
    fi

    consul(){
      sudo docker run --rm -it --net host r.j3ss.co/consul $@
    }

    nomad(){
      sudo docker run --rm -it --net host \
        -v $(pwd):/usr/src \
        --workdir /usr/src \
        r.j3ss.co/nomad $@
    }
